export enum PROPERTIES_CATEGORIES {
  RESIDENTIAL = "residential",
  COMMERCIAL = "commercial",
  INTERNATIONAL = "international",
}

export enum PROPERTIES_DATA_KEYS {
  REAL_ESTATE = "realEstateType",
  READY_TO_MOVE = "readyToMove",
  UPDATE_CONTACT_INFO = "updateContactInfo",
  APARTMENT_TYPE = "apartmentType",
  FITTINGS = "fitting",
  FURNISHING = "furnishing",
  BEDROOM = "bedroom",
  BATHROOM = "bathroom",
  SQUARE_METERS = "squareMeters",
  KITCHEN = "kitchen",
  PARKING = "parking",
  AC_TYPE = "acType",
  HAS_KAHRAMA = "hasKahramaa",
  HAS_INTERNET = "hasInternet",
  GENDER = "gender",
  RENTAL_PERIOD = "rentalPeriod",
  DEPOSIT = "deposit",
  COMMISSION = "commission",
  COMMISSION_TYPE = "commissionType",
  COMMISSION_VALUE = "commissionValue",
  DOWN_PAYMENT = "downpayment",
  DOWN_PAYMENT_VALUE = "downpaymentValue",
  PRICE_FREQUENCY = "priceFrequency",
  PRICE = "price",
  PRICE_MIN = "priceMin",
  PRICE_MAX = "priceMax",
  FREE_MONTH = "freeMonth",
  TITLE = "title",
  DESCRIPTION = "description",
  FEATURE = "feature",
  CONTACT_MOBILE = "contactMobile",
  CONTACT_WHATSAPP = "contactWhatsapp",
  CONTACT_EMAIL = "contactEmail",
  REFERENCE_NUMBER = "referenceNumber",
  AGENT = "userId",
  SHOW_EXACT_LOCATION = "showExactLocation",
  BLUE_PLATE = "bluePlate",
  ZONE = "zone",
  STREET = "street",
  BUILDING = "building",
  LOCATION = "location",
  PROPERTIES_MAP = "propertiesMap",
  LANGUAGE = "language",
  NATIONALITY = "nationality",
  CITY = "city",
  COUNTRY = "country",
  FIRST_NAME = "firstName",
  LAST_NAME = "lastName",
  PROFILE_PICTURE = "profilePicture",
  USER_NAME = "userName",
  MESSAGE = "message",
  USERNAME_EMAIL_PHONE = "username_email_phone",
  PASSWORD = "password",
  CONFIRM_PASSWORD = "confirmPassword",
  DESIGNATION = "designation",
  LICENSE_NUMBER = "licenseNumber",
  LICENSE_FILE = "licenseFile",
  AGENCY_NAME = "agencyName",
  COMPANY_EMAIL = "companyEmail",
  CR_NUMBER = "crNumber",
  UPLOAD_CR_ATTACHMENT = "uploadCRAttachment",
  ABOUT_AGENCY = "aboutAgency",
  ADDRESS = "Address",
  AGENT_NAME = "agentName",
  SHORT_BIO = "bio",
  AGENCY_LOGO = "agencyLogoUri",
  CATEGORIES = "categories",
  FEEDBACK = "feedback",

  // TODO: Need to check following usage
  COMMENT = "comment",
  DISCOUNTED_PRICE = "discountedPrice",
  DISCOUNT_PERCENTAGE = "discountPercentage",
}

export const PROPERTIES_SEARCH_FILTERS = Object.freeze({
  PURPOSE: "purpose",
  CATEGORY: "category",
  PROPERTY_TYPE: "propertyTypes",
  ANY: "Any",
  ALL: "All",
  ...PROPERTIES_DATA_KEYS,
  ...PROPERTIES_CATEGORIES,
  OTHERS: "others",
  LOCATION: "location",
  KEY_WORDS: "keywords",
  USER: "user",
  STATUS: "status",
  MIN_PRICE: "minPrice",
  MAX_PRICE: "maxPrice",
  SORT_BY: "sortby",
  FURNISHING: "furnishing",
  COMPANY_NAMES: "companyNames",
  AREA_NAMES: "areaNames",
  CITY_NAMES: "cityNames",
  COUNTRY_NAMES: "countryNames",
  ZONE_NAMES: "zoneNames",
  COMPANY_USER_ID: "companyUserId",
  USER_ID: "userId",
  LICENSED_ONLY: "licensedOnly",
});