export const enum PAGINATION_DEFAULTS {
  DEFAULT_CUR_PAGE = 1,
  DEFAULT_PER_PAGE = 10,
  DEFAULT_MAP_PER_PAGE = 9,
  MAX_LENGTH = 80,
  DASHBOARD_DEFAULT_PER_PAGE = 25,
  AGENT_AGENCY_DEFAULT_PER_PAGE = 15,
}
